### PR TITLE
Allow for installation on projects using Composer 2

### PR DESCRIPTION
**Pull request by bobdenotter**
Hi, it'd be great if we could use this package on composer 2 as well. 

Thanks!

### CODE REVIEW

**Comment by I-Valchev** [comment]
Any progress on this?

**Comment by bobdenotter** [comment]
Hi, @allanpaiste, 

Is this project still maintained?

**Comment by japerry** [comment]
I put a request out to Vaimo a few weeks ago regarding this and some other composer modules they support. Unfortunately I have not received a message back. I did look to see if the main developer of this still worked there, and alas he does not. So I have forked all of these modules under the LANFest Org (we're also using these dependencies) and updated them (and dependencies) to support Composer 2. They're live on packagist today.

**Comment by bobdenotter** [comment]
@japerry What a coincidence! I forked 'em too this weekend, but I only did the bare necessities for our project: 

 - https://packagist.org/packages/bolt/binary-chromedriver 
 - https://packagist.org/packages/bolt/webdriver-binary-downloader 

It's working correctly for us, now.. At a first glance I don't see any changes in your fork. For me, the trickiest part was getting it to download stuff in https://github.com/LANFest/webdriver-binary-downloader/blob/master/src/Managers/DownloadManager.php#L128 

If you intend to keep the forks updated, I'm more than happy to deprecate ours right away!

**Comment by japerry** [comment]
Oh, hah I didn't see that. Yup we plan on keeping maintenance of it, feel free to make PRs there. I have to bring in vaimo's other binary drivers, which will happen sometime this sprint. We cleaned up some of their other processes as well.

I made a PR from your work here: https://github.com/LANFest/webdriver-binary-downloader/pull/1 

Also, same goes with us, if you guys want to maintain it, we're happy to push PRs to your fork instead!

**Comment by bobdenotter** [comment]
@japerry I think I'd prefer to lend a hand with getting your forks up to speed. Probably later this week, i'll switch to your fork, and make some PR's where needed!

**Pull request closed without merging**
